systemLog:
  destination: file
  path: "c:/data/cryptotitans/mongodb.log"
  logAppend: true
storage:
  engine: wiredTiger
  dbPath: "c:/data/cryptotitans"
  journal:
    enabled: true
net:
  bindIp: 127.0.0.1,127.0.1.1,HydraOrc
  port: 27017
replication:
  replSetName: 'cryptotitans'
