export const cafes = [
  {
    id: '1',
    name: 'Studentencafé De Boschpoort',
    location: 'Delhi, India',
    image: '/img/cafe1.png',
    region: 'north',
  },
  {
    id: '2',
    name: 'Studentencafé De Boschpoort',
    location: 'Bangalore, India',
    image: '/img/cafe2.png',
    region: 'south',
  },
  {
    id: '3',
    name: 'Studentencafé De Boschpoort',
    location: 'Delhi, India',
    image: '/img/cafe3.png',
    region: 'north',
  },
  {
    id: '4',
    name: 'Studentencafé De Boschpoort',
    location: 'Delhi, India',
    image: '/img/cafe4.png',
    region: 'north',
  },
  {
    id: '5',
    name: 'Studentencafé De Boschpoort',
    location: 'Bangalore, India',
    image: '/img/cafe5.png',
    region: 'south',
  },
  {
    id: '6',
    name: 'Studentencafé De Boschpoort',
    location: 'Delhi, India',
    image: '/img/cafe6.png',
    region: 'north',
  },
  {
    id: '7',
    name: 'Studentencafé De Boschpoort',
    location: 'Delhi, India',
    image: '/img/cafe1.png',
    region: 'north',
  },
  {
    id: '8',
    name: 'Studentencafé De Boschpoort',
    location: 'Delhi, India',
    image: '/img/cafe2.png',
    region: 'north',
  },
];
