export const cafes = [
  {
    id: '1',
    name: 'Studentencafé De Boschpoort',
    location: 'Delhi, India',
    image: '/img/cafe1.jpg',
    region: 'north',
    distance: '1 mile away',
  },
  {
    id: '2',
    name: 'Café Le Flambeau',
    location: 'Bangalore, India',
    image: '/img/cafe2.jpeg',
    region: 'south',
    distance: '2 miles away',
  },
  {
    id: '3',
    name: 'The Brew House',
    location: 'Mumbai, India',
    image: '/img/cafe3.jpeg',
    region: 'west',
    distance: '3 miles away',
  },
  {
    id: '4',
    name: 'Coffee Junction',
    location: 'Delhi, India',
    image: '/img/cafe4.jpg',
    region: 'north',
    distance: '4 miles away',
  },
  {
    id: '5',
    name: 'Java Café',
    location: 'Chennai, India',
    image: '/img/cafe5.jpg',
    region: 'south',
    distance: '5 miles away',
  },
  {
    id: '6',
    name: 'Chai Palace',
    location: 'Kolkata, India',
    image: '/img/cafe4.jpg',
    region: 'east',
    distance: '6 miles away',
  },
  {
    id: '7',
    name: 'Tea Leaf Café',
    location: 'Pune, India',
    image: '/img/cafe1.jpg',
    region: 'west',
    distance: '7 miles away',
  },
  {
    id: '8',
    name: 'Mocha Brews',
    location: 'Hyderabad, India',
    image: '/img/cafe2.jpeg',
    region: 'south',
    distance: '8 miles away',
  },
  {
    id: '9',
    name: 'Espresso Hub',
    location: 'Jaipur, India',
    image: '/img/cafe3.jpeg',
    region: 'north',
    distance: '9 miles away',
  },
  {
    id: '10',
    name: 'Green Tea Garden',
    location: 'Coimbatore, India',
    image: '/img/cafe4.jpg',
    region: 'south',
    distance: '10 miles away',
  },
  {
    id: '11',
    name: 'Aromatic Beans Café',
    location: 'Ahmedabad, India',
    image: '/img/cafe5.jpg',
    region: 'west',
    distance: '11 miles away',
  },
  {
    id: '12',
    name: 'Morning Dew Café',
    location: 'Lucknow, India',
    image: '/img/cafe1.jpg',
    region: 'north',
    distance: '12 miles away',
  },
  {
    id: '13',
    name: 'Sunset Brews',
    location: 'Visakhapatnam, India',
    image: '/img/cafe2.jpeg',
    region: 'south',
    distance: '13 miles away',
  },
  {
    id: '14',
    name: 'Golden Bean Coffee',
    location: 'Guwahati, India',
    image: '/img/cafe3.jpeg',
    region: 'east',
    distance: '14 miles away',
  },
  {
    id: '15',
    name: 'Himalayan Chai House',
    location: 'Shimla, India',
    image: '/img/cafe4.jpg',
    region: 'north',
    distance: '15 miles away',
  },
  {
    id: '16',
    name: 'Coconut Brew Café',
    location: 'Kochi, India',
    image: '/img/cafe5.jpg',
    region: 'south',
    distance: '16 miles away',
  },
  {
    id: '17',
    name: 'Spice Route Café',
    location: 'Bhubaneswar, India',
    image: '/img/cafe1.jpg',
    region: 'east',
    distance: '17 miles away',
  },
  {
    id: '18',
    name: 'Lotus Tea Lounge',
    location: 'Chandigarh, India',
    image: '/img/cafe2.jpeg',
    region: 'north',
    distance: '18 miles away',
  },
  {
    id: '19',
    name: 'Oceanic Brews',
    location: 'Goa, India',
    image: '/img/cafe3.jpeg',
    region: 'west',
    distance: '19 miles away',
  },
  {
    id: '20',
    name: 'Mountain View Café',
    location: 'Dehradun, India',
    image: '/img/cafe4.jpg',
    region: 'north',
    distance: '20 miles away',
  },

  {
    id: '125',
    name: 'Morning Dew Café',
    location: 'Lucknow, India',
    image: '/img/cafe1.jpg',
    region: 'north',
    distance: '12 miles away',
  },
  {
    id: '132',
    name: 'Sunset Brews',
    location: 'Visakhapatnam, India',
    image: '/img/cafe2.jpeg',
    region: 'south',
    distance: '13 miles away',
  },
  {
    id: '142',
    name: 'Golden Bean Coffee',
    location: 'Guwahati, India',
    image: '/img/cafe3.jpeg',
    region: 'east',
    distance: '14 miles away',
  },
  {
    id: '152',
    name: 'Himalayan Chai House',
    location: 'Shimla, India',
    image: '/img/cafe4.jpg',
    region: 'north',
    distance: '15 miles away',
  },
  {
    id: '162',
    name: 'Coconut Brew Café',
    location: 'Kochi, India',
    image: '/img/cafe5.jpg',
    region: 'south',
    distance: '16 miles away',
  },
  {
    id: '172',
    name: 'Spice Route Café',
    location: 'Bhubaneswar, India',
    image: '/img/cafe1.jpg',
    region: 'east',
    distance: '17 miles away',
  },
  {
    id: '182',
    name: 'Lotus Tea Lounge',
    location: 'Chandigarh, India',
    image: '/img/cafe2.jpeg',
    region: 'north',
    distance: '18 miles away',
  },
  {
    id: '192',
    name: 'Oceanic Brews',
    location: 'Goa, India',
    image: '/img/cafe3.jpeg',
    region: 'west',
    distance: '19 miles away',
  },
  {
    id: '202',
    name: 'Mountain View Café',
    location: 'Dehradun, India',
    image: '/img/cafe4.jpg',
    region: 'north',
    distance: '20 miles away',
  },
];
